FROM python:3.8.12-slim-bullseye

ENV PYTHONUNBUFFERED 1

RUN mkdir /drf
WORKDIR /drf
COPY ./drf /drf
RUN pip install -r requirements.txt

RUN sh -c "python manage.py makemigrations"
RUN sh -c "python manage.py migrate"
RUN python -c "import django; django.setup(); \
   from django.contrib.auth.management.commands.createsuperuser import get_user_model; \
   get_user_model()._default_manager.db_manager('$DJANGO_DB_NAME').create_superuser( \
   username='$DJANGO_SU_NAME', \
   email='$DJANGO_SU_EMAIL', \
   password='$DJANGO_SU_PASSWORD')"